server.port=8903
spring.datasource.url=jdbc:mysql://u9ynq6gemhfk4xlr:kX1BxXG8z5VAwozloKyz@b6hw1rs7wtrxjvr6v0h0-mysql.services.clever-cloud.com:3306/b6hw1rs7wtrxjvr6v0h0
spring.datasource.username=b6hw1rs7wtrxjvr6v0h0
spring.datasource.password=kX1BxXG8z5VAwozloKyz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.encoding=UTF-8
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.ddl-auto= none
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hieuhv203@gmail.com
spring.mail.password=yqdw armu rqlc aoyr
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=25
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.session.store-type=none