server:
  port: 8920
logging:
  level:
    org:
      springframework:
        security: DEBUG
#redis:
#  redisson:
#    host: redis://127.0.0.1:6379
#    connection-pool-size: 10
#    connection-minimum-idle-size: 5
#    connect-timeout: 30000
redis:
  redisson:
    host: rediss://pet-albacore-37760.upstash.io:6379
    connection-pool-size: 10
    connection-minimum-idle-size: 5
    connect-timeout: 10000
    password: AZOAAAIjcDE1MmJkNjg3YjA3YmE0YjhjOTIwMWQxYmQyODZjMDM5YnAxMA

spring:
  application:
    name: MusicApp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
# Database deploy
#    username: root
#    password: LbAjfhGflNGkOWqdHKQCKBKfOhYwcSZo
#    url: jdbc:mysql://mainline.proxy.rlwy.net:39722/railway
# Data test from company
#    username: root
#    password: 892003
#    url: jdbc:mysql://localhost:3306/sublime
# Data test from house
    username: unpsnrlgyfso2rer
    password: kOlSLR7VlFfUOxIw751M
    url: jdbc:mysql://bqjwzjflx1ofrecsasko-mysql.services.clever-cloud.com:3306/bqjwzjflx1ofrecsasko
    sql:
      init:
        encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hieuhv203@gmail.com
    password: npnm hfzj ufhr tksj
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000