server:
  port: 8903
spring:
  session:
    store-type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 08092003
    url: jdbc:mysql://localhost:3306/Sublime
  sql:
    init:
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: hieuhv203@gmail.com
    password: yqdw armu rqlc aoyr
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true
  #spring.datasource.url=jdbc:mysql://uutnyjb26ldpzah8:CdeJw8HmW9cK3MUV6Z3P@bllwvg06ean0ccxexjdp-mysql.services.clever-cloud.com:3306/bllwvg06ean0ccxexjdp
  #spring.datasource.username=uutnyjb26ldpzah8
  #spring.datasource.password=CdeJw8HmW9cK3MUV6Z3P